# version: '3.9'

# services:
#   db: # Conatiner de MySQL
#     image: mysql:5.7 # FROM mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     env_file:
#       - ./config/db.env
#     networks:
#       - backend

#   wordpress:
#     depends_on:
#       - db
#     image: wordpress:latest
#     volumes:
#       - wordpress_data:/var/www/html
#     ports:
#       - "8000:80"
#     restart: always
#     env_file:
#       - ./config/wp.env
#     networks:
#       - backend

# volumes:
#   db_data: {}
#   wordpress_data: {}
  
# networks:
#   backend:
#     driver: bridge


version: '3.3'

services:
  mariadb:
    image: mariadb
    env_file:
      - ./config/db.env
    volumes:
      - ./database:/var/lib/mysql
      
  wordpress:
    image: wordpress
    links:
      - mariadb:mysql
    env_file:
      - ./config/wp.env
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html