version: '3.9'

services:
  db: # Conatiner de MySQL
    image: mysql:5.7 # FROM mysql:7.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
volumes:
  db_data: {}
  wordpress_data: {}